LOG_ENTRY_SEVERITY(   TRACE,        (1<<__LINE__),    "[TRACE]",     LOG_COLOR_GRAY    )
LOG_ENTRY_SEVERITY(   INFO,         (1<<__LINE__),    "[INFO ]",     LOG_COLOR_GREEN   )
LOG_ENTRY_SEVERITY(   WARN,         (1<<__LINE__),    "[WARN ]",     LOG_COLOR_YELLOW  )
LOG_ENTRY_SEVERITY(   ERROR,        (1<<__LINE__),    "[ERROR]",     LOG_COLOR_RED     )
LOG_ENTRY_SEVERITY(   FATAL,        (1<<__LINE__),    "[FATAL]",     LOG_COLOR_PURPLE  )
LOG_ENTRY_SEVERITY(   EMPTY0,                   0,    "[     ]",     LOG_COLOR_GRAY    )
LOG_ENTRY_SUBSYSTEM(  PLATFORM,     (1<<__LINE__),    "[PLATF]",     LOG_COLOR_CYAN    )
LOG_ENTRY_SUBSYSTEM(  AUDIO,        (1<<__LINE__),    "[AUDIO]",     LOG_COLOR_GREEN   )
LOG_ENTRY_SUBSYSTEM(  VIDEO,        (1<<__LINE__),    "[VIDEO]",     LOG_COLOR_RED     )
LOG_ENTRY_SUBSYSTEM(  NETWORK,      (1<<__LINE__),    "[NETWK]",     LOG_COLOR_PURPLE  )
LOG_ENTRY_SUBSYSTEM(  TEST,         (1<<__LINE__),    "[TEST ]",     LOG_COLOR_GREEN   )
LOG_ENTRY_SUBSYSTEM(  EMPTY1,                   0,    "[     ]",     LOG_COLOR_GRAY    )
LOG_ENTRY_CATEGORY(   INIT,         (1<<__LINE__),    "[INIT ]",     LOG_COLOR_GRAY    )
LOG_ENTRY_CATEGORY(   SHUTDOWN,     (1<<__LINE__),    "[SHUTD]",     LOG_COLOR_GRAY    )
LOG_ENTRY_CATEGORY(   ACTIVATE,     (1<<__LINE__),    "[ACTIV]",     LOG_COLOR_GRAY    )
LOG_ENTRY_CATEGORY(   DEACTIVATE,   (1<<__LINE__),    "[DEACT]",     LOG_COLOR_GRAY    )
LOG_ENTRY_CATEGORY(   EMPTY2,                   0,    "[     ]",     LOG_COLOR_GRAY    )
