/* entry             name         value   string     color          */
LOG_ENTRY_SEVERITY(  TRACE,      (1<<0),  "[TRACE]", LOG_COLOR_GRAY  )
LOG_ENTRY_SEVERITY(  INFO,       (1<<1),  "[INFO ]", LOG_COLOR_GREEN )
LOG_ENTRY_SEVERITY(  WARN,       (1<<2),  "[WARN ]", LOG_COLOR_YELLOW)
LOG_ENTRY_SEVERITY(  ERROR,      (1<<3),  "[ERROR]", LOG_COLOR_RED   )
LOG_ENTRY_SEVERITY(  FATAL,      (1<<4),  "[FATAL]", LOG_COLOR_PURPLE)

LOG_ENTRY_SUBSYSTEM( PLATFORM,   (1<<5),  "[PLATF]", LOG_COLOR_YELLOW )
LOG_ENTRY_SUBSYSTEM( AUDIO,      (1<<6),  "[AUDIO]", LOG_COLOR_YELLOW )
LOG_ENTRY_SUBSYSTEM( VIDEO,      (1<<7),  "[VIDEO]", LOG_COLOR_YELLOW )
LOG_ENTRY_SUBSYSTEM( NETWORK,    (1<<8),  "[NETWK]", LOG_COLOR_YELLOW )
LOG_ENTRY_SUBSYSTEM( TEST,       (1<<9),  "[TEST ]", LOG_COLOR_YELLOW )

LOG_ENTRY_CATEGORY(  INIT,       (1<<20), "[INIT ]", LOG_COLOR_PURPLE)
LOG_ENTRY_CATEGORY(  SHUTDOWN,   (1<<21), "[SHUTD]", LOG_COLOR_OFF   )
LOG_ENTRY_CATEGORY(  ACTIVATE,   (1<<22), "[ACTIV]", LOG_COLOR_PURPLE)
LOG_ENTRY_CATEGORY(  DEACTIVATE, (1<<23), "[DEACT]", LOG_COLOR_PURPLE)
